#!/bin/bash
echo  "Input the firstdir..."
# To check which direct have more files
read a
#read file number 
echo "Input the second dir..."
# check secound file in file
read b
#read second file 
    C1=$(find $a -type f | wc -l)
    C2=$(find $b -type f | wc -l)
    if [ $C1 -gt $C2 ]
         then
         echo "first Directory has more files"
         #first file has more files
    else if [ $C2 -gt $C1 ]
         then
         echo "Second Directory has greater number of files"
         #second file has more files in file
    else
         echo "Both Directories have same number of files"
         #Both files have the same files in file.
    fi
    fi
