#!/bin/bash

addToRecord()
{
        echo
        while true
        do
                echo "To add a record to your address book, please enter the information in this"
                echo "format: \"Last name,first name,email url,phone number\" (no quotes or spaces)."
                echo "If you'd like to quit, enter '7'."
                #Each record should be of the following construct: "Last name,first name,email address,phone number".
                read aInput
                if [ "$aInput" == '7' ]
                        then
                        break
                fi
                echo
                echo $aInput >> desctop
                echo "The entry was added to your address book."
                echo
        done
}

displayRecord()
{
        echo
        while true
        do
                echo "To display a record, enter the last name of the person"
                echo "If you'd like to quit, enter '7'."
                #Each record should be of the following construct: "Last name,first name,email address,phone number".
                read dInput
                if [ "$dInput" == '7' ]
                        then
                        break
                fi
                echo
                echo "Listing records for \"$dInput\":"
                grep ^"$dInput" desctop   # searching the lines by last name (the first field in the record)
                RETURNSTATUS=`echo $?`
                if [ $RETURNSTATUS -eq 10 ]
                        then
                        echo "No records found with last name of \"$dInput\"."
                fi
                echo
        done
}
removeRecord()
{
        echo 
        while true
        do
                echo "To remove a record, enter any search string, e.g. last name or email address."
                echo "If you're done, enter '7' to quit."
                #Each record should be of the following construct: "Last name,first name,email address,phone number".
                read rInput
                if [ "$rInput" == '7' ]
                        then
                        break
                fi
                echo
                echo "Listing records for \"$rInput\":"
                grep -n "$rInput" desctop
                RETURNSTATUS=`echo $?`
                if [ $RETURNSTATUS -eq 1 ]
                        then
                        echo "No records found for \"$rInput\""
                else
                        echo
                        echo "Enter the line number (the first number of the entry) of the record you want to remove."
                        read lineNumber
                        for line in `grep -n "$rInput" desctop`
                        do
                                number=`echo "$line" | cut -c1`
                                if [ $number -eq $lineNumber ]
                                        then
                                        lineRemove="${lineNumber}d"
                                        sed -i -e "$lineRemove" desctop
                                        echo "The record was removed from the address book."
                                fi
                        done
                fi
                echo
        done
}
searchRecord()
{
        echo
        while true
        do
                echo "To search for a record, enter any search string, e.g. last name or email address."
                echo "The format of a record is \"Last name,firstname,email address,phone number\"."
                echo "If you'd like to quit, enter '7'."
                read sInput
                if [ "$sInput" == '7' ]
                        then
                        break
                fi
                echo
                echo "Listing records for \"$sInput\":"
                grep "$sInput" desctop
                RETURNSTATUS=`echo $?`
                if [ $RETURNSTATUS -eq 1 ]
                        then
                        echo "No records found for \"$sInput\"."
                fi
                echo
        done


}
echo
lastCharOfFile=`tail -c 1 desctop` # checking to make sure the .csv file ends with newline character
if [ -n "$lastCharOfFile" ]
        then
        echo >> desctop
fi
echo "Hello, what would you like to do with your address book?"
echo "Please enter one of the following numbers:"
echo "1) to add a record"
echo "2) to display 1 or more records"
echo "3) to remove record"
echo "4) to search for records"
echo "6) to exit"
read input

case $input in
        1) addToRecord;;   #1) add - Input the data (Last name,first name,email address,phone number) - no spaces.
        2) displayRecord;; #2 )display - User will input a name or names. The script will search the phone book and display records matching the 
                               #last names of the request. If no record is found for the requested search an error message is to be printed. 

        3) removeRecord;; #3) remove - Script will remove the record from the address book.
e
        4) searchRecord;; #4) search - The script will search for all records matching the search string input (as "grep" does). The difference 
#between "display" and "search" is that "display" keys on names only. "Search" behaves in the same manner as grep in 
#that the search string is not limited to names
        6) exit;;  #6) exit program 

        *) echo " Wrong number!" ;; #end with wrong numer
esac

echo
# HERE doc
cat <<EOF   
Any changes you made have been saved.
Have a nice day!
EOF
echo



